### ISSUE TITLE
Can we have "target temp." back in fan control?

### ISSUE THREAD

**Issue by sunfic** [jaschaknack/PolarisBiosEditor#26]
Actually it is the only useful parameter for real fan control. I tried all other parameters they are not working as we think.

**Comment by jaschaknack** [comment]
Hi,
maybe fuzzy logic is on? Try to set this to 0 if it is 1.
Kind Regards

**Comment by DeCoRawr** [comment]
Don't set fuzzy mode to 0, you will not be able to use graphic once driver set up.

Yeah i agree with sunfic, target temperature is the only parameter that works. I need to use other PBE, then check for differences since it mess with timings and set it with hex editor and then crc. 

Making target temp avaliable in this will be really great ;)

datspike version have target tempareture but it's outdated, i checked diff and it's no big deal to implement.

My 2 cents

**Comment by abhspire** [comment]
Similar request regarding fan control. Any changes I have made to the fan settings (min/med/high temps and min/med/high PWM %) seem to be ignored when running Claymore 10.0 or 7.3 on both Window 10 and ethOS. Fan never spins past ~30% even as temps climb into the 70s. I can override this in Radeon Global WattMan settings, but would like to have them written to the BIOS so they are default parameters regardless of OS. Well done with the v1.6.6 one-click Ubermix; great hashrates. Please let me know what other info I can provide on this, logs, screenshots, etc.

**Comment by jaschaknack** [comment]
Can you link me the repository where the feature you want is properly implemented?

**Comment by DeCoRawr** [comment]
https://github.com/datspike/PolarisBiosEditor

thank you ;)

**Comment by charlesrg** [comment]
I added, just clone and build.sh and you will have your binary with the feature.

**Comment by jaschaknack** [comment]
I merged the pull request and will build a new executable for windows users this week. Thank you @charlesrg @DeCoRawr for the effort.
