### ISSUE TITLE
Missing FanControlMode? 

### ISSUE THREAD

**Issue by renaudcerrato** [jaschaknack/PolarisBiosEditor#3]
None of the FAN settings are working on any of my  Sapphire RX480. From what I've read, Sapphire fan control is using some fuzzy logic instead. Where's the FanControlMode setting?

**Comment by jaschaknack** [comment]
Thank you for your suggestion. I've implemented the feature for you, have a look at version 1.5. To get the right parameter, I suggest you compare the Sapphire Setting with some other BIOS file where fuzzy logic is not used. Please report your results.

**Comment by renaudcerrato** [comment]
Amazing! So fast! Will have a look at the setting on Tuesday. I was about to wrote my own `fancontrol` systemd service, you saved my ass.

I'm a dev, I'm willing to help, submit PR or even port it to Linux. Where do you get those offsets and significations ? Is there some kind of documentation or C structure somewhere?

**Comment by jaschaknack** [comment]
I forked this project originally to run it on Linux because the .NET implementation used WPF, a non availible part in mono. If you have the mono runtime installed, mono PolarisBiosEditor.exe should work with my version. The offsets are not found by me, the Linux Kernel contains some of the structure:
https://github.com/torvalds/linux/blob/master/drivers/gpu/drm/amd/powerplay/hwmgr/pptable_v1_0.h

Also notice this thread at overclock.net:
http://www.overclock.net/t/1604567/polaris-bios-editing-rx5xx-rx4xx

**Comment by renaudcerrato** [comment]
Amazing. Thanks!

**Comment by renaudcerrato** [comment]
Hey @jaschaknack : the FanControlMode flag is working perfectly! Thanks for that. I had to force 0 in order to get those fan settings meaningful:

![image](https://cloud.githubusercontent.com/assets/1930949/26587179/9e6bfa6c-451f-11e7-963d-a0c4128475e7.png)

Just a comment: I'd change the name to `Fan Control Mode` or `Fuzzy Mode` instead.

**Comment by jaschaknack** [comment]
Thank you for your response. I'll alter the description to 'Fuzzy Mode' in the next release.
